// <auto-generated />
using System;
using TRVisionAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TRVisionAI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316063848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TRVisionAI.Data.Entities.FrameEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApiSentAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FrameNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaskImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("NgCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolutionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Verdict")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiSentAt");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("TRVisionAI.Data.Entities.ModuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FrameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Verdict")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TRVisionAI.Data.Entities.SessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NgCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TRVisionAI.Data.Entities.FrameEntity", b =>
                {
                    b.HasOne("TRVisionAI.Data.Entities.SessionEntity", "Session")
                        .WithMany("Frames")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TRVisionAI.Data.Entities.ModuleEntity", b =>
                {
                    b.HasOne("TRVisionAI.Data.Entities.FrameEntity", "Frame")
                        .WithMany("Modules")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("TRVisionAI.Data.Entities.FrameEntity", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("TRVisionAI.Data.Entities.SessionEntity", b =>
                {
                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
